// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type featuresTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *featuresTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("features").
func (v *featuresTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *featuresTableType) Columns() []string {
	return []string{
		"id",
		"key",
		"description",
		"enabled",
		"value",
		"created_at",
		"updated_at",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *featuresTableType) NewStruct() reform.Struct {
	return new(Features)
}

// NewRecord makes a new record for that table.
func (v *featuresTableType) NewRecord() reform.Record {
	return new(Features)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *featuresTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// FeaturesTable represents features view or table in SQL database.
var FeaturesTable = &featuresTableType{
	s: parse.StructInfo{
		Type:    "Features",
		SQLName: "features",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "string", Column: "id"},
			{Name: "Key", Type: "string", Column: "key"},
			{Name: "Description", Type: "*string", Column: "description"},
			{Name: "Enabled", Type: "bool", Column: "enabled"},
			{Name: "Value", Type: "json.RawMessage", Column: "value"},
			{Name: "CreatedAt", Type: "time.Time", Column: "created_at"},
			{Name: "UpdatedAt", Type: "time.Time", Column: "updated_at"},
		},
		PKFieldIndex: 0,
	},
	z: new(Features).Values(),
}

// String returns a string representation of this struct or record.
func (s Features) String() string {
	res := make([]string, 7)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Key: " + reform.Inspect(s.Key, true)
	res[2] = "Description: " + reform.Inspect(s.Description, true)
	res[3] = "Enabled: " + reform.Inspect(s.Enabled, true)
	res[4] = "Value: " + reform.Inspect(s.Value, true)
	res[5] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	res[6] = "UpdatedAt: " + reform.Inspect(s.UpdatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Features) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Key,
		s.Description,
		s.Enabled,
		s.Value,
		s.CreatedAt,
		s.UpdatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Features) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Key,
		&s.Description,
		&s.Enabled,
		&s.Value,
		&s.CreatedAt,
		&s.UpdatedAt,
	}
}

// View returns View object for that struct.
func (s *Features) View() reform.View {
	return FeaturesTable
}

// Table returns Table object for that record.
func (s *Features) Table() reform.Table {
	return FeaturesTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Features) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Features) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Features) HasPK() bool {
	return s.ID != FeaturesTable.z[FeaturesTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Features) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = FeaturesTable
	_ reform.Struct = (*Features)(nil)
	_ reform.Table  = FeaturesTable
	_ reform.Record = (*Features)(nil)
	_ fmt.Stringer  = (*Features)(nil)
)

func init() {
	parse.AssertUpToDate(&FeaturesTable.s, new(Features))
}
